name: Build

on:
  push:
    branches:
      - main
      - build
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Update cargo
        run: rustup update

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}

      - name: Build
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/release/staticauth
